/* The following code was generated by JFlex 1.6.1 */

package analizador;

import java_cup.runtime.*;
import java.util.ArrayList;
import Errores.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/analizador/lexico.jflex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int comentariosimple = 2;
  public static final int comentariomultiple = 4;
  public static final int stringSecuenciasEscapes = 6;
  public static final int stringSecuenciasEscapes2 = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 47, 48, 51, 50, 50,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    47, 33, 52, 49,  0, 30, 35,  0, 22, 23, 27, 25, 39, 26, 41, 28, 
    40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 37, 38, 32, 24, 31, 34, 
     0, 10, 11,  8, 14,  3,  2, 42,  9, 43, 42, 45,  4, 42, 17, 16, 
    42, 42, 12, 44,  7, 15, 42,  6, 42, 42, 42, 20, 53, 21, 29, 46, 
     0, 10, 11,  8, 14,  3,  2, 42,  9, 43, 42, 45,  4, 42, 17, 16, 
    42, 42, 12, 44,  7, 15, 42,  6, 42, 42, 42, 18, 36, 19,  0,  0, 
     0,  0,  0,  0,  0, 51,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0, 42,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0, 42,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\2\1\3\2\1\1\7\2\1\3\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\1\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\1\2\2\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\34\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\4\2"+
    "\1\0\7\2\1\51\1\2\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\1\0\1\47\1\50\1\2\1\60\1\61"+
    "\2\2\1\62\1\0\1\2\2\0\2\2\1\0\6\2"+
    "\1\63\1\2\1\0\2\2\2\64\2\0\1\2\1\65"+
    "\2\66\4\2\1\67\1\2\2\70\1\2\1\0\2\71"+
    "\1\0\1\2\2\72\3\2\1\0\1\2\1\73\1\0"+
    "\1\2\1\74\1\2\1\73\1\0\1\2\1\0\1\2"+
    "\1\75\2\76\2\77";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\u0144\0\u017a"+
    "\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a"+
    "\0\u0360\0\u0396\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e"+
    "\0\u03cc\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e\0\u0402\0\u0438"+
    "\0\u046e\0\u04a4\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e"+
    "\0\u04da\0\u0510\0\u0546\0\u057c\0\u010e\0\u05b2\0\u010e\0\u010e"+
    "\0\u010e\0\u010e\0\u05e8\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e"+
    "\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e\0\u061e\0\u0654\0\u068a"+
    "\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798\0\u07ce\0\u0804\0\u083a"+
    "\0\u0870\0\u01e6\0\u08a6\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e"+
    "\0\u010e\0\u08dc\0\u01e6\0\u01e6\0\u0912\0\u010e\0\u010e\0\u0948"+
    "\0\u097e\0\u01e6\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2"+
    "\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c\0\u08dc"+
    "\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\u010e\0\u01e6\0\u0d4a\0\u0d80"+
    "\0\u0db6\0\u01e6\0\u010e\0\u01e6\0\u0dec\0\u0e22\0\u0e58\0\u0e8e"+
    "\0\u01e6\0\u0ec4\0\u010e\0\u01e6\0\u0efa\0\u0f30\0\u010e\0\u01e6"+
    "\0\u0f66\0\u0f9c\0\u010e\0\u01e6\0\u0fd2\0\u1008\0\u103e\0\u1074"+
    "\0\u10aa\0\u010e\0\u10e0\0\u1116\0\u01e6\0\u114c\0\u01e6\0\u1182"+
    "\0\u11b8\0\u11ee\0\u1224\0\u01e6\0\u010e\0\u01e6\0\u010e\0\u01e6";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\2\12\1\17\1\20\1\6\1\21\2\12\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\12\1\53\1\54\1\12\1\6\2\55\1\56\1\55"+
    "\1\0\1\57\1\6\60\60\1\61\1\60\2\62\35\60"+
    "\1\63\24\60\1\62\1\60\1\62\1\0\2\60\60\64"+
    "\1\55\1\64\1\55\1\0\1\65\1\66\7\6\1\67"+
    "\4\6\1\70\4\6\1\71\35\6\2\55\1\6\1\55"+
    "\1\0\1\72\1\73\70\0\1\74\16\0\1\75\46\0"+
    "\3\12\1\0\4\12\1\76\2\12\1\0\1\12\1\77"+
    "\1\100\1\12\26\0\7\12\11\0\2\12\1\101\1\0"+
    "\7\12\1\0\4\12\26\0\7\12\11\0\3\12\1\0"+
    "\7\12\1\0\4\12\26\0\7\12\15\0\1\102\61\0"+
    "\3\12\1\0\3\12\1\103\3\12\1\0\4\12\26\0"+
    "\7\12\11\0\3\12\1\0\6\12\1\104\1\0\4\12"+
    "\26\0\7\12\11\0\3\12\1\0\4\12\1\105\2\12"+
    "\1\0\2\12\1\106\1\12\26\0\7\12\11\0\3\12"+
    "\1\0\6\12\1\107\1\0\4\12\26\0\7\12\11\0"+
    "\1\12\1\110\1\12\1\0\7\12\1\0\4\12\26\0"+
    "\7\12\11\0\1\12\1\111\1\12\1\0\7\12\1\0"+
    "\2\12\1\112\1\12\26\0\7\12\11\0\3\12\1\0"+
    "\7\12\1\0\1\12\1\113\2\12\26\0\7\12\37\0"+
    "\1\114\6\0\1\115\64\0\1\116\57\0\1\117\65\0"+
    "\1\120\65\0\1\121\105\0\1\51\1\122\16\0\3\12"+
    "\1\0\7\12\1\0\4\12\30\0\4\12\12\0\1\123"+
    "\2\12\1\0\7\12\1\0\3\12\1\124\26\0\7\12"+
    "\11\0\3\12\1\0\1\125\6\12\1\0\4\12\26\0"+
    "\7\12\42\0\1\126\113\0\1\127\6\0\2\12\1\130"+
    "\1\0\7\12\1\0\4\12\26\0\7\12\11\0\3\12"+
    "\1\0\7\12\1\0\3\12\1\131\26\0\7\12\11\0"+
    "\3\12\1\0\6\12\1\132\1\0\4\12\26\0\7\12"+
    "\11\0\3\12\1\133\7\12\1\0\4\12\26\0\4\12"+
    "\1\134\2\12\10\0\1\135\51\0\1\135\13\0\1\136"+
    "\3\12\1\0\7\12\1\0\4\12\26\0\3\12\1\137"+
    "\3\12\11\0\3\12\1\0\7\12\1\0\1\12\1\140"+
    "\2\12\26\0\7\12\11\0\3\12\1\141\7\12\1\0"+
    "\4\12\26\0\4\12\1\142\2\12\11\0\3\12\1\0"+
    "\7\12\1\0\3\12\1\143\26\0\7\12\11\0\1\12"+
    "\1\144\1\12\1\0\7\12\1\0\4\12\26\0\7\12"+
    "\11\0\3\12\1\0\1\12\1\145\5\12\1\0\4\12"+
    "\26\0\7\12\11\0\1\146\2\12\1\0\7\12\1\0"+
    "\4\12\26\0\7\12\11\0\2\12\1\147\1\0\7\12"+
    "\1\0\4\12\26\0\7\12\57\0\1\150\16\0\1\135"+
    "\3\12\1\0\7\12\1\0\4\12\26\0\3\12\1\151"+
    "\3\12\11\0\3\12\1\152\7\12\1\0\4\12\26\0"+
    "\4\12\1\153\2\12\11\0\3\12\1\0\2\12\1\154"+
    "\4\12\1\0\4\12\26\0\7\12\12\0\1\155\64\0"+
    "\1\12\1\156\1\12\1\0\7\12\1\0\4\12\26\0"+
    "\7\12\16\0\1\157\62\0\1\160\63\0\2\12\1\161"+
    "\1\0\7\12\1\0\4\12\26\0\7\12\11\0\1\12"+
    "\1\162\1\12\1\0\7\12\1\0\4\12\26\0\7\12"+
    "\12\0\1\163\64\0\1\12\1\164\1\12\1\0\7\12"+
    "\1\0\4\12\26\0\7\12\11\0\3\12\1\0\1\12"+
    "\1\165\5\12\1\0\4\12\26\0\7\12\11\0\3\12"+
    "\1\0\4\12\1\166\2\12\1\0\4\12\26\0\7\12"+
    "\11\0\3\12\1\0\7\12\1\0\1\12\1\167\2\12"+
    "\26\0\7\12\11\0\3\12\1\0\4\12\1\170\2\12"+
    "\1\0\4\12\26\0\7\12\11\0\2\12\1\171\1\0"+
    "\7\12\1\0\4\12\26\0\7\12\11\0\3\12\1\0"+
    "\1\12\1\172\5\12\1\0\4\12\26\0\7\12\12\0"+
    "\1\173\64\0\1\12\1\174\1\12\1\0\7\12\1\0"+
    "\4\12\26\0\7\12\11\0\3\12\1\0\1\12\1\175"+
    "\5\12\1\0\4\12\26\0\7\12\17\0\1\176\60\0"+
    "\1\177\64\0\1\12\1\200\1\12\1\0\7\12\1\0"+
    "\4\12\26\0\7\12\10\0\1\201\3\12\1\0\7\12"+
    "\1\0\4\12\26\0\3\12\1\202\3\12\11\0\3\12"+
    "\1\0\7\12\1\203\4\12\26\0\5\12\1\204\1\12"+
    "\11\0\3\12\1\0\6\12\1\205\1\0\4\12\26\0"+
    "\7\12\11\0\3\12\1\0\7\12\1\0\1\12\1\206"+
    "\2\12\26\0\7\12\11\0\3\12\1\0\2\12\1\207"+
    "\4\12\1\0\4\12\26\0\7\12\10\0\1\210\3\12"+
    "\1\0\7\12\1\0\4\12\26\0\3\12\1\211\3\12"+
    "\20\0\1\212\75\0\1\213\46\0\3\12\1\0\7\12"+
    "\1\0\3\12\1\214\26\0\7\12\11\0\3\12\1\0"+
    "\7\12\1\0\3\12\1\215\26\0\7\12\11\0\2\12"+
    "\1\216\1\0\7\12\1\0\4\12\26\0\7\12\11\0"+
    "\3\12\1\0\3\12\1\217\3\12\1\0\4\12\26\0"+
    "\7\12\27\0\1\220\47\0\3\12\1\0\7\12\1\0"+
    "\2\12\1\221\1\12\26\0\7\12\26\0\1\222\50\0"+
    "\3\12\1\0\7\12\1\0\1\12\1\223\2\12\26\0"+
    "\7\12\11\0\3\12\1\0\1\12\1\224\5\12\1\0"+
    "\4\12\26\0\7\12\30\0\1\225\46\0\3\12\1\0"+
    "\7\12\1\0\3\12\1\226\26\0\7\12\12\0\1\227"+
    "\64\0\1\12\1\230\1\12\1\0\7\12\1\0\4\12"+
    "\26\0\7\12\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4698];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\14\1\6\11\1\1\5\11\4\1\6\11"+
    "\4\1\1\11\1\1\4\11\1\1\12\11\4\1\1\0"+
    "\11\1\6\11\1\0\3\1\2\11\3\1\1\0\1\1"+
    "\2\0\2\1\1\0\10\1\1\0\2\1\1\11\1\1"+
    "\2\0\2\1\1\11\7\1\1\11\2\1\1\0\1\11"+
    "\1\1\1\0\1\1\1\11\4\1\1\0\1\1\1\11"+
    "\1\0\4\1\1\0\1\1\1\0\2\1\1\11\1\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //cod
    //metodo para error
    String ERcadena = "";
    public static ArrayList<ErrorE> errorLexico = new ArrayList<ErrorE>();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("ERROR LEXICO: <<"+yytext()+">> Linea: "+yyline+" ,Columna: "+yycolumn);
                            //errorLexico.add(new ErrorE("ERROR LEXICO: <<" +yytext()+ ">> Linea: "+yyline+" ,Columna: "+yycolumn));
                            errorLexico.add(new ErrorE(yytext(), yyline, yycolumn));
                            ;
            }
          case 64: break;
          case 2: 
            { System.out.println("Reconocido: <<"+yytext()+">>, id");
                                return new Symbol(sym.id, yyline, yycolumn, yytext());
            }
          case 65: break;
          case 3: 
            { System.out.println("Reconocido: <<"+yytext()+">>, allave");
                                return new Symbol(sym.allave, yyline, yycolumn, yytext());
            }
          case 66: break;
          case 4: 
            { System.out.println("Reconocido: <<"+yytext()+">>, cllave");
                                return new Symbol(sym.cllave, yyline, yycolumn, yytext());
            }
          case 67: break;
          case 5: 
            { System.out.println("Reconocido: <<"+yytext()+">>, acorchete");
                                return new Symbol(sym.acorchete, yyline, yycolumn, yytext());
            }
          case 68: break;
          case 6: 
            { System.out.println("Reconocido: <<"+yytext()+">>, ccorchete");
                                return new Symbol(sym.ccorchete, yyline, yycolumn, yytext());
            }
          case 69: break;
          case 7: 
            { System.out.println("Reconocido: <<"+yytext()+">>, aparentesis");
                                return new Symbol(sym.aparentesis, yyline, yycolumn, yytext());
            }
          case 70: break;
          case 8: 
            { System.out.println("Reconocido: <<"+yytext()+">>, cparentesis");
                                return new Symbol(sym.cparentesis, yyline, yycolumn, yytext());
            }
          case 71: break;
          case 9: 
            { System.out.println("Reconocido: <<"+yytext()+">>, igual");
                                return new Symbol(sym.igual, yyline, yycolumn, yytext());
            }
          case 72: break;
          case 10: 
            { System.out.println("Reconocido: <<"+yytext()+">>, suma");
                                return new Symbol(sym.suma, yyline, yycolumn, yytext());
            }
          case 73: break;
          case 11: 
            { System.out.println("Reconocido: <<"+yytext()+">>, resta");
                                return new Symbol(sym.resta, yyline, yycolumn, yytext());
            }
          case 74: break;
          case 12: 
            { System.out.println("Reconocido: <<"+yytext()+">>, por");
                                return new Symbol(sym.por, yyline, yycolumn, yytext());
            }
          case 75: break;
          case 13: 
            { System.out.println("Reconocido: <<"+yytext()+">>, division");
                                return new Symbol(sym.division, yyline, yycolumn, yytext());
            }
          case 76: break;
          case 14: 
            { System.out.println("Reconocido: <<"+yytext()+">>, potencia");
                                return new Symbol(sym.potencia, yyline, yycolumn, yytext());
            }
          case 77: break;
          case 15: 
            { System.out.println("Reconocido: <<"+yytext()+">>, mayorq");
                                return new Symbol(sym.mayorq, yyline, yycolumn, yytext());
            }
          case 78: break;
          case 16: 
            { System.out.println("Reconocido: <<"+yytext()+">>, menorq");
                                return new Symbol(sym.menorq, yyline, yycolumn, yytext());
            }
          case 79: break;
          case 17: 
            { System.out.println("Reconocido: <<"+yytext()+">>, not");
                                return new Symbol(sym.not, yyline, yycolumn, yytext());
            }
          case 80: break;
          case 18: 
            { System.out.println("Reconocido: <<"+yytext()+">>, interrogacion");
                                return new Symbol(sym.interrogacion, yyline, yycolumn, yytext());
            }
          case 81: break;
          case 19: 
            { System.out.println("Reconocido: <<"+yytext()+">>, and");
                                return new Symbol(sym.and, yyline, yycolumn, yytext());
            }
          case 82: break;
          case 20: 
            { System.out.println("Reconocido: <<"+yytext()+">>, or");
                                return new Symbol(sym.or, yyline, yycolumn, yytext());
            }
          case 83: break;
          case 21: 
            { System.out.println("Reconocido: <<"+yytext()+">>, dospuntos");
                                return new Symbol(sym.dospuntos, yyline, yycolumn, yytext());
            }
          case 84: break;
          case 22: 
            { System.out.println("Reconocido: <<"+yytext()+">>, puntoycoma");
                                return new Symbol(sym.puntoycoma, yyline, yycolumn, yytext());
            }
          case 85: break;
          case 23: 
            { System.out.println("Reconocido: <<"+yytext()+">>, coma");
                                return new Symbol(sym.coma, yyline, yycolumn, yytext());
            }
          case 86: break;
          case 24: 
            { System.out.println("Reconocido: <<"+yytext()+">>, ERnumero");
                                return new Symbol(sym.ERnumero, yyline, yycolumn, yytext());
            }
          case 87: break;
          case 25: 
            { /* ignore white space. */
            }
          case 88: break;
          case 26: 
            { yybegin(comentariosimple);
            }
          case 89: break;
          case 27: 
            { yybegin(stringSecuenciasEscapes); ERcadena ="";
            }
          case 90: break;
          case 28: 
            { /* omitilo weeeeeee */
            }
          case 91: break;
          case 29: 
            { yybegin(YYINITIAL);
                                        System.out.println("Comentario simple: <<"+yytext()+">> Linea: "+yyline+" ,Columna: "+yycolumn);
            }
          case 92: break;
          case 30: 
            { 
            }
          case 93: break;
          case 31: 
            { ERcadena += yytext();
            }
          case 94: break;
          case 32: 
            { System.out.println(ERcadena); yybegin(YYINITIAL); 
                                return new Symbol(sym.cadena, yyline, yycolumn, ERcadena);
            }
          case 95: break;
          case 33: 
            { yybegin(stringSecuenciasEscapes2);
            }
          case 96: break;
          case 34: 
            { System.out.println("\t"); ERcadena += "\t"; yybegin(stringSecuenciasEscapes);
            }
          case 97: break;
          case 35: 
            { System.out.println("\r"); ERcadena += "\r"; yybegin(stringSecuenciasEscapes);
            }
          case 98: break;
          case 36: 
            { System.out.println("\n"); ERcadena += "\n"; yybegin(stringSecuenciasEscapes);
            }
          case 99: break;
          case 37: 
            { System.out.println("\""); ERcadena += "\""; yybegin(stringSecuenciasEscapes);
            }
          case 100: break;
          case 38: 
            { System.out.println("\\"); ERcadena += "\\" ; yybegin(stringSecuenciasEscapes);
            }
          case 101: break;
          case 39: 
            { System.out.println("Reconocido: <<"+yytext()+">>, iff");
                                return new Symbol(sym.iff, yyline, yycolumn, yytext());
            }
          case 102: break;
          case 40: 
            { System.out.println("Reconocido: <<"+yytext()+">>, inn");
                                return new Symbol(sym.inn, yyline, yycolumn, yytext());
            }
          case 103: break;
          case 41: 
            { System.out.println("Reconocido: <<"+yytext()+">>, doo");
                                return new Symbol(sym.doo, yyline, yycolumn, yytext());
            }
          case 104: break;
          case 42: 
            { System.out.println("Reconocido: <<"+yytext()+">>, igualigual");
                                return new Symbol(sym.igualigual, yyline, yycolumn, yytext());
            }
          case 105: break;
          case 43: 
            { System.out.println("Reconocido: <<"+yytext()+">>, flecha");
                                return new Symbol(sym.flecha, yyline, yycolumn, yytext());
            }
          case 106: break;
          case 44: 
            { System.out.println("Reconocido: <<"+yytext()+">>, modulo");
                                return new Symbol(sym.modulo, yyline, yycolumn, yytext());
            }
          case 107: break;
          case 45: 
            { System.out.println("Reconocido: <<"+yytext()+">>, mayorigualq");
                                return new Symbol(sym.mayorigualq, yyline, yycolumn, yytext());
            }
          case 108: break;
          case 46: 
            { System.out.println("Reconocido: <<"+yytext()+">>, menorigualq");
                                return new Symbol(sym.menorigualq, yyline, yycolumn, yytext());
            }
          case 109: break;
          case 47: 
            { System.out.println("Reconocido: <<"+yytext()+">>, diferente");
                                return new Symbol(sym.diferente, yyline, yycolumn, yytext());
            }
          case 110: break;
          case 48: 
            { yybegin(comentariomultiple);
            }
          case 111: break;
          case 49: 
            { yybegin(YYINITIAL);
                                        System.out.println("Comentario multiple: <<"+yytext()+">> Linea: "+yyline+" ,Columna: "+yycolumn);
            }
          case 112: break;
          case 50: 
            { System.out.println("Reconocido: <<"+yytext()+">>, forr");
                                return new Symbol(sym.forr, yyline, yycolumn, yytext());
            }
          case 113: break;
          case 51: 
            { System.out.println("Reconocido: <<"+yytext()+">>, ERdecimal");
                                return new Symbol(sym.ERdecimal, yyline, yycolumn, yytext());
            }
          case 114: break;
          case 52: 
            { System.out.println("Reconocido: <<"+yytext()+">>, elsee");
                                return new Symbol(sym.elsee, yyline, yycolumn, yytext());
            }
          case 115: break;
          case 53: 
            { System.out.println("Reconocido: <<"+yytext()+">>, truee");
                                return new Symbol(sym.truee, yyline, yycolumn, yytext());
            }
          case 116: break;
          case 54: 
            { System.out.println("Reconocido: <<"+yytext()+">>, casee");
                                return new Symbol(sym.casee, yyline, yycolumn, yytext());
            }
          case 117: break;
          case 55: 
            { System.out.println("Reconocido: <<"+yytext()+">>, nulo");
                                return new Symbol(sym.nulo, yyline, yycolumn, yytext());
            }
          case 118: break;
          case 56: 
            { System.out.println("Reconocido: <<"+yytext()+">>, falsee");
                                return new Symbol(sym.falsee, yyline, yycolumn, yytext());
            }
          case 119: break;
          case 57: 
            { System.out.println("Reconocido: <<"+yytext()+">>, whilee");
                                return new Symbol(sym.whilee, yyline, yycolumn, yytext());
            }
          case 120: break;
          case 58: 
            { System.out.println("Reconocido: <<"+yytext()+">>, breakk");
                                return new Symbol(sym.breakk, yyline, yycolumn, yytext());
            }
          case 121: break;
          case 59: 
            { System.out.println("Reconocido: <<"+yytext()+">>, switchh");
                                return new Symbol(sym.switchh, yyline, yycolumn, yytext());
            }
          case 122: break;
          case 60: 
            { System.out.println("Reconocido: <<"+yytext()+">>, returnn");
                                return new Symbol(sym.returnn, yyline, yycolumn, yytext());
            }
          case 123: break;
          case 61: 
            { System.out.println("Reconocido: <<"+yytext()+">>, defaultt");
                                return new Symbol(sym.defaultt, yyline, yycolumn, yytext());
            }
          case 124: break;
          case 62: 
            { System.out.println("Reconocido: <<"+yytext()+">>, functionn");
                                return new Symbol(sym.functionn, yyline, yycolumn, yytext());
            }
          case 125: break;
          case 63: 
            { System.out.println("Reconocido: <<"+yytext()+">>, continuee");
                                return new Symbol(sym.continuee, yyline, yycolumn, yytext());
            }
          case 126: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
