
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 11 21:11:07 CST 2020
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ccorchete = 21;
  public static final int doo = 9;
  public static final int ERnumero = 48;
  public static final int igualigual = 35;
  public static final int allave = 18;
  public static final int resta = 26;
  public static final int suma = 25;
  public static final int cllave = 19;
  public static final int unegativo = 45;
  public static final int falsee = 11;
  public static final int switchh = 4;
  public static final int flecha = 44;
  public static final int mayorq = 31;
  public static final int acorchete = 20;
  public static final int coma = 43;
  public static final int nulo = 16;
  public static final int igual = 24;
  public static final int upositivo = 46;
  public static final int elsee = 3;
  public static final int puntoycoma = 42;
  public static final int casee = 5;
  public static final int functionn = 15;
  public static final int returnn = 14;
  public static final int truee = 10;
  public static final int iff = 2;
  public static final int EOF = 0;
  public static final int menorq = 32;
  public static final int whilee = 7;
  public static final int error = 1;
  public static final int breakk = 6;
  public static final int or = 39;
  public static final int por = 27;
  public static final int forr = 8;
  public static final int mayorigualq = 33;
  public static final int defaultt = 17;
  public static final int dospuntos = 41;
  public static final int id = 50;
  public static final int potencia = 29;
  public static final int cparentesis = 23;
  public static final int menorigualq = 34;
  public static final int inn = 12;
  public static final int ERdecimal = 49;
  public static final int diferente = 36;
  public static final int aparentesis = 22;
  public static final int not = 40;
  public static final int and = 38;
  public static final int continuee = 13;
  public static final int division = 28;
  public static final int interrogacion = 37;
  public static final int modulo = 30;
  public static final int cadena = 47;
}

