
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 22 22:46:37 CST 2020
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int puntoycoma = 64;
  public static final int forr = 10;
  public static final int nulo = 34;
  public static final int ccorchete = 43;
  public static final int print = 9;
  public static final int barplot = 37;
  public static final int acorchete = 42;
  public static final int typeoff = 20;
  public static final int suma = 47;
  public static final int removee = 26;
  public static final int hist = 39;
  public static final int cllave = 41;
  public static final int continuee = 15;
  public static final int nCol = 22;
  public static final int resta = 48;
  public static final int dospuntos = 63;
  public static final int functionn = 17;
  public static final int elsee = 3;
  public static final int ERnumero = 69;
  public static final int doo = 11;
  public static final int menorq = 54;
  public static final int inn = 14;
  public static final int touppercase = 28;
  public static final int trunkk = 29;
  public static final int arrayy = 23;
  public static final int modee = 33;
  public static final int interrogacion = 59;
  public static final int mayorq = 53;
  public static final int tolowercase = 27;
  public static final int lengthh = 21;
  public static final int menorigualq = 56;
  public static final int casee = 5;
  public static final int listt = 19;
  public static final int or = 61;
  public static final int mayorigualq = 55;
  public static final int whilee = 8;
  public static final int id = 71;
  public static final int breakk = 6;
  public static final int c = 18;
  public static final int defaultt = 7;
  public static final int upositivo = 68;
  public static final int matrix = 35;
  public static final int truee = 12;
  public static final int and = 60;
  public static final int cparentesis = 45;
  public static final int returnn = 16;
  public static final int iff = 2;
  public static final int meann = 31;
  public static final int division = 50;
  public static final int EOF = 0;
  public static final int nrow = 24;
  public static final int flecha = 66;
  public static final int switchh = 4;
  public static final int mediann = 32;
  public static final int potencia = 51;
  public static final int roundd = 30;
  public static final int error = 1;
  public static final int diferente = 58;
  public static final int stringlength = 25;
  public static final int igualigual = 57;
  public static final int ERdecimal = 70;
  public static final int allave = 40;
  public static final int por = 49;
  public static final int aparentesis = 44;
  public static final int coma = 65;
  public static final int pie = 36;
  public static final int modulo = 52;
  public static final int falsee = 13;
  public static final int plot = 38;
  public static final int not = 62;
  public static final int igual = 46;
  public static final int unegativo = 67;
}

